
<h1 style="text-align: center;">CIÊNCIA DE DADOS</h1>
<h1 style="text-align: center;">Roteiro de Atividade Prática</h1>
<br>
<br>

Nome: ______________________________________________________________________________________      

Turma: ______________


**Componente:** Inteligência Artificial 
<br>
**Unidade Curricular:** Processamento de Linguagem Natural
<br>
**Tema da Semana:** Processamento de linguagem natural
<br>

# Aula 3: Exercícios de Fixação

## Tarefa
- Execute o código abaixo.

- Se as bibliotecas não tiverem instaladas, instale-as.

- Acompanhe as instruções.

- Preencha o código onde está #TO DO

- Responda as perguntas e conclua a atividade

### Código

### Instalação das dependências

In [1]:
!pip install nltk pandas gensim scikit-learn

Requirement already satisfied: nltk in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (3.9.1)
Requirement already satisfied: pandas in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: gensim in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (4.3.3)
Requirement already satisfied: scikit-learn in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (1.5.2)
Requirement already satisfied: click in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from nltk) (4.66.6)
Requirement already satisfied: numpy>=1.26.0 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from gensim) (7.0.5)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: wrapt in /home/janes/dev/projects/seduc/ano2/seduc/lib/python3.12/site-packages (from smart-open>=1.8.1->gensim) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

### Imports de dependências

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/janes/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity
import nltk

### Configurações

In [4]:
pd.set_option("display.max_colwidth", None)  # Exibe o conteúdo completo das células
pd.set_option("display.max_rows", None)  # Exibe todas as linhas sem truncar

### Leitura dos dados

In [5]:
dados = {
    "descricao_original": [
        "Compra no supermercado Eee",
        "Pagamento de conta de luz",
        "Transferência recebida",
        "Assinatura mensal streaming Nnn",
        "Jantar no restaurante italiano",
        "Compra de gasolina no posto Sss",
        "Pagamento de aluguel",
        "Compra de roupas na loja Zzz",
        "Compra de eletrônicos no Mmm",
        "Compra de livros na Aaa",
        "Compra de remédios na farmácia",
        "Pagamento de fatura do cartão",
        "Compra de móveis para a casa",
        "Assinatura de música Sss",
        "Transferência enviada para João"
    ]
}

df = pd.DataFrame(dados)

### Transformações básicas do texto

In [6]:
def preprocessamento(texto):
    texto = re.sub(r'[^\w\s]', '', texto)
    return texto.lower()

df['descricao'] = df['descricao_original'].apply(preprocessamento)

### Apresentação dos dados

In [7]:
df

                 descricao_original                        descricao
0        Compra no supermercado Eee       compra no supermercado eee
1         Pagamento de conta de luz        pagamento de conta de luz
2            Transferência recebida           transferência recebida
3   Assinatura mensal streaming Nnn  assinatura mensal streaming nnn
4    Jantar no restaurante italiano   jantar no restaurante italiano
5   Compra de gasolina no posto Sss  compra de gasolina no posto sss
6              Pagamento de aluguel             pagamento de aluguel
7      Compra de roupas na loja Zzz     compra de roupas na loja zzz
8      Compra de eletrônicos no Mmm     compra de eletrônicos no mmm
9           Compra de livros na Aaa          compra de livros na aaa
10   Compra de remédios na farmácia   compra de remédios na farmácia
11    Pagamento de fatura do cartão    pagamento de fatura do cartão
12     Compra de móveis para a casa     compra de móveis para a casa
13         Assinatura de música Sss         assinatura de música sss
14  Transferência enviada para João  transferência enviada para joão

### Tokenização

In [8]:
df['tokens'] = df['descricao'].apply(word_tokenize)
df[['descricao', 'tokens']]

                          descricao                                  tokens
0        compra no supermercado eee         [compra, no, supermercado, eee]
1         pagamento de conta de luz         [pagamento, de, conta, de, luz]
2            transferência recebida               [transferência, recebida]
3   assinatura mensal streaming nnn    [assinatura, mensal, streaming, nnn]
4    jantar no restaurante italiano     [jantar, no, restaurante, italiano]
5   compra de gasolina no posto sss  [compra, de, gasolina, no, posto, sss]
6              pagamento de aluguel                [pagamento, de, aluguel]
7      compra de roupas na loja zzz     [compra, de, roupas, na, loja, zzz]
8      compra de eletrônicos no mmm      [compra, de, eletrônicos, no, mmm]
9           compra de livros na aaa           [compra, de, livros, na, aaa]
10   compra de remédios na farmácia    [compra, de, remédios, na, farmácia]
11    pagamento de fatura do cartão     [pagamento, de, fatura, do, cartão]
12     compra de móveis para a casa     [compra, de, móveis, para, a, casa]
13         assinatura de música sss           [assinatura, de, música, sss]
14  transferência enviada para joão    [transferência, enviada, para, joão]

### Criação e treinamento do modelo Word2Vec

In [9]:
#TO DO
# Configurações: vetor de 10 dimensões, janela de contexto de 2 palavras, e 5 iterações de treinamento
model = Word2Vec(sentences=df['tokens'], vector_size=10, window=2, min_count=1, epochs=5)
#model = Word2Vec(sentences=df['tokens'], vector_size=30, window=2, min_count=1, epochs=5)

### Função para gerar vetores médios das palavras em uma descrição

In [10]:
def obter_embedding_medio(tokens, model):
    # Gera a média dos embeddings de cada token presente no modelo
    vetor_palavras = [model.wv[word] for word in tokens if word in model.wv]
    if len(vetor_palavras) > 0:
        return sum(vetor_palavras) / len(vetor_palavras)
    else:
        return [0] * model.vector_size

### Geração embeddings para cada transação

In [11]:
df['embedding'] = df['tokens'].apply(lambda tokens: obter_embedding_medio(tokens, model))

In [12]:
df

,descricao_original,descricao,tokens,embedding
0,Compra no supermercado Eee,compra no supermercado eee,"[compra, no, supermercado, eee]","[0.019185703, 0.0070857434, 0.038719933, -0.022412805, 0.02363626, -0.010953829, -0.00741528, 0.0032074964, -0.037140496, -0.02855784]"
1,Pagamento de conta de luz,pagamento de conta de luz,"[pagamento, de, conta, de, luz]","[-0.035332985, 0.018667525, 0.020203445, 0.039171368, -0.0031059086, -0.031284552, -0.005069951, 0.053142853, -0.0139778275, 0.0038289255]"
2,Transferência recebida,transferência recebida,"[transferência, recebida]","[-0.031072535, -0.014226235, 0.025853429, -0.03405264, 0.029899463, -0.018024966, 0.02137911, 0.077287346, -0.055989616, -0.014404236]"
3,Assinatura mensal streaming Nnn,assinatura mensal streaming nnn,"[assinatura, mensal, streaming, nnn]","[0.043792788, -0.040893897, -0.03525368, -0.0043805875, 0.020771256, 0.036472, 0.06595431, 0.010812396, 0.016968776, 0.070377246]"
4,Jantar no restaurante italiano,jantar no restaurante italiano,"[jantar, no, restaurante, italiano]","[-0.009598582, -0.0051448154, 0.024351362, -0.014226797, 0.01607672, -0.005205809, 0.012776232, -0.012208265, -0.01115074, 0.008804553]"
5,Compra de gasolina no posto Sss,compra de gasolina no posto sss,"[compra, de, gasolina, no, posto, sss]","[0.03214848, 0.01138055, -0.010911897, 0.021408364, 0.012638923, 0.004663971, 0.03162353, 0.041825414, -0.0592825, -0.033769254]"
6,Pagamento de aluguel,pagamento de aluguel,"[pagamento, de, aluguel]","[-0.05759598, 0.02160444, -0.03612539, 0.007909349, -0.018733354, -0.005274324, 1.6471682e-05, 0.06897552, -0.013811398, 0.04229775]"
7,Compra de roupas na loja Zzz,compra de roupas na loja zzz,"[compra, de, roupas, na, loja, zzz]","[-0.03157275, 0.0075897, 0.021268247, 0.025134884, -0.0072202403, -0.015927076, 0.05622426, -0.0014985552, -0.037159625, -0.056710403]"
8,Compra de eletrônicos no Mmm,compra de eletrônicos no mmm,"[compra, de, eletrônicos, no, mmm]","[0.040429477, 0.0095909275, 0.027595729, 0.050342996, -0.011532003, -0.0458375, 0.004568039, 0.061647933, -0.057793207, -0.049413137]"
9,Compra de livros na Aaa,compra de livros na aaa,"[compra, de, livros, na, aaa]","[0.014069286, 0.0060177036, 0.013594398, -0.008440738, -0.030645598, -0.01634355, 0.044623345, 0.022169994, -0.021611908, -0.04925579]"
10,Compra de remédios na farmácia,compra de remédios na farmácia,"[compra, de, remédios, na, farmácia]","[0.003362177, -0.016498184, 0.024947746, 0.031305738, -0.044703834, 0.0008881822, 0.06572243, 0.0038687005, -0.04129578, -0.015548785]"
11,Pagamento de fatura do cartão,pagamento de fatura do cartão,"[pagamento, de, fatura, do, cartão]","[-0.027025059, 0.049838707, 0.018582797, -0.015392673, 0.023378853, -0.01658998, 0.032544162, 0.041379582, 0.012217727, -0.004513487]"
12,Compra de móveis para a casa,compra de móveis para a casa,"[compra, de, móveis, para, a, casa]","[0.025839224, -0.009161924, 0.01727621, 0.043102313, -0.04843707, 0.0082742125, 0.04663181, 0.011871743, -0.029609665, -0.0007961678]"
13,Assinatura de música Sss,assinatura de música sss,"[assinatura, de, música, sss]","[-0.0045250608, 0.026093172, -0.018922163, -0.017959282, -0.013875871, -0.042377945, 0.04145477, -0.007373079, -0.044160113, -0.017117351]"
14,Transferência enviada para João,transferência enviada para joão,"[transferência, enviada, para, joão]","[-0.0100638345, -0.022893155, -0.024846762, -0.029118398, -0.019725567, -0.0052534463, 0.033124436, 0.023251494, -0.027405418, 0.030300569]"

### Calculo de similaridade entre transações

In [13]:
similaridade = cosine_similarity(list(df['embedding']))

### Apresentação dos resultados

In [14]:
# Função para exibir as três transações mais semelhantes para uma transação específica
def exibir_similares(transacao, df, similaridade):
    idx = df.index[df['descricao_original'] == transacao].tolist()[0]
    similaridades = list(enumerate(similaridade[idx]))
    similares_ordenados = sorted(similaridades, key=lambda x: x[1], reverse=True)
    print(f"\nTransação: {transacao}")
    for i, score in similares_ordenados[1:4]:  # Mostra as 3 mais semelhantes
        print(f"- Similar a: '{df.iloc[i]['descricao']}' (similaridade: {score:.2f})")

In [15]:
# Exemplos de similaridade
exibir_similares('Assinatura mensal streaming Nnn', df, similaridade)
exibir_similares('Transferência recebida', df, similaridade)

Transação: Assinatura mensal streaming Nnn
- Similar a: 'transferência enviada para joão' (similaridade: 0.51)
- Similar a: 'compra de móveis para a casa' (similaridade: 0.22)
- Similar a: 'compra de remédios na farmácia' (similaridade: 0.12)

Transação: Transferência recebida
- Similar a: 'pagamento de fatura do cartão' (similaridade: 0.53)
- Similar a: 'compra no supermercado eee' (similaridade: 0.53)
- Similar a: 'compra de gasolina no posto sss' (similaridade: 0.51)

### Perguntas e Conclusão

#### Crie uma cópia o tamanho do vetor de embedding de 10 para 30.
##### Visualmente o resultado ficou melhor com 30 dimensões?